# Generated by Django 5.1.5 on 2025-02-03 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('source_logo', models.URLField(blank=True, null=True)),
                ('source_website', models.CharField(max_length=100)),
                ('date_posted', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
