# Generated by Django 5.1.5 on 2025-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_job_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_number', models.IntegerField(default=1)),
                ('interval_frequency', models.CharField(choices=[('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('days', 'Days')], default='hours', max_length=10)),
            ],
        ),
    ]
